---
- hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Check if java is installed
      command: java -version
      register: java_result
      ignore_errors: True

    - debug:
        msg: "Failed - Java is not installed"
      when: java_result is failed

    - debug:
        msg: "Success - Java is installed"
      when: java_result is success
